### PR TITLE
Feat: Model mapper changes aligned with AAS 3.0 standard

### PR DESCRIPTION
**Pull request by agg3fe**
## Description

- Changes done according to AAS 3.0 standard.
- JPA entities and mappers are changed. 
- New models and tables are created.
- Liquibase script has been changed.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:
- [x] Copyright and license header are present on all affected files

### Additional information

The PR is bigger than the expected 1000 lines because of new AAS 3.0 standard changes, which includes database changes and model changes.

### CODE REVIEW

**Review by tunacicek — APPROVED** [review]
LGTM

**Comment by SebastianBezold** [comment]
Before merging, wait for the project content review: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9749

**Comment by tunacicek** [comment]
@SebastianBezold : do you have an update on this PR?

**Comment by SebastianBezold** [comment]
> @SebastianBezold : do you have an update on this PR?

Hi @tunacicek , from my point of view the PR is fine, but the project content review linked above is still open

**Comment by tunacicek** [comment]
Content review is done (approved):  https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9749
We will merge the PR

**Pull request merged**
